#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libogg
Version  : 1.3.5
Release  : 40
URL      : https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.xz
Source0  : https://downloads.xiph.org/releases/ogg/libogg-1.3.5.tar.xz
Summary  : Ogg Bitstream Library Development
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libogg-lib = %{version}-%{release}
Requires: libogg-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
Patch1: fmv.patch

%description
Libogg is a library for manipulating ogg bitstreams.  It handles
both making ogg bitstreams and getting packets from ogg bitstreams.

%package dev
Summary: dev components for the libogg package.
Group: Development
Requires: libogg-lib = %{version}-%{release}
Provides: libogg-devel = %{version}-%{release}
Requires: libogg = %{version}-%{release}

%description dev
dev components for the libogg package.


%package dev32
Summary: dev32 components for the libogg package.
Group: Default
Requires: libogg-lib32 = %{version}-%{release}
Requires: libogg-dev = %{version}-%{release}

%description dev32
dev32 components for the libogg package.


%package doc
Summary: doc components for the libogg package.
Group: Documentation

%description doc
doc components for the libogg package.


%package lib
Summary: lib components for the libogg package.
Group: Libraries
Requires: libogg-license = %{version}-%{release}

%description lib
lib components for the libogg package.


%package lib32
Summary: lib32 components for the libogg package.
Group: Default
Requires: libogg-license = %{version}-%{release}

%description lib32
lib32 components for the libogg package.


%package license
Summary: license components for the libogg package.
Group: Default

%description license
license components for the libogg package.


%prep
%setup -q -n libogg-1.3.5
cd %{_builddir}/libogg-1.3.5
%patch1 -p1
pushd ..
cp -a libogg-1.3.5 build32
popd
pushd ..
cp -a libogg-1.3.5 buildavx2
popd
pushd ..
cp -a libogg-1.3.5 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656131397
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=256 "
export FCFLAGS="$FFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=256 "
export FFLAGS="$FFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=256 "
export CXXFLAGS="$CXXFLAGS -Ofast -falign-functions=32 -fno-lto -fno-semantic-interposition -mprefer-vector-width=256 "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx512/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256 -Wl,-z,x86-64-v4"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256 -Wl,-z,x86-64-v4"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v4 -mprefer-vector-width=256"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v4"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || :
cd ../buildavx512;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1656131397
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libogg
cp %{_builddir}/libogg-1.3.5/COPYING %{buildroot}/usr/share/package-licenses/libogg/bc252631805cf037048f64fef562f98c2a0bdc9e
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd ../buildavx2/
%make_install_v3
popd
pushd ../buildavx512/
%make_install_v4
popd
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/lib64/haswell/avx512_1/pkgconfig/ogg.pc
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/ogg/config_types.h
/usr/include/ogg/ogg.h
/usr/include/ogg/os_types.h
/usr/lib64/libogg.so
/usr/lib64/pkgconfig/ogg.pc
/usr/share/aclocal/*.m4

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libogg.so
/usr/lib32/pkgconfig/32ogg.pc
/usr/lib32/pkgconfig/ogg.pc

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/libogg/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/glibc-hwcaps/x86-64-v3/libogg.so
/usr/lib64/glibc-hwcaps/x86-64-v3/libogg.so.0
/usr/lib64/glibc-hwcaps/x86-64-v3/libogg.so.0.8.5
/usr/lib64/glibc-hwcaps/x86-64-v4/libogg.so
/usr/lib64/glibc-hwcaps/x86-64-v4/libogg.so.0
/usr/lib64/glibc-hwcaps/x86-64-v4/libogg.so.0.8.5
/usr/lib64/libogg.so.0
/usr/lib64/libogg.so.0.8.5

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libogg.so.0
/usr/lib32/libogg.so.0.8.5

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libogg/bc252631805cf037048f64fef562f98c2a0bdc9e
